# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "GymBud" do

pod 'RSDayFlow', '~> 0.1.2'
pod 'MLPAutoCompleteTextField', '~> 1.5'
pod 'AFNetworking', '~> 2.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'Mixpanel'
pod 'AXRatingView'
pod 'JSQMessagesViewController'
pod 'UIAlertView-Blocks'

end

target "GymBudTests" do

end

