# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "GymBud" do

pod 'RSDayFlow', '~> 0.1.2'
pod 'MLPAutoCompleteTextField', '~> 1.5'

end

target "GymBudTests" do

end

